"use strict";
exports.__esModule = true;
var checkForGameOver_1 = require("./checkForGameOver");
exports.checkForGameOver = checkForGameOver_1["default"];
var levelUp_1 = require("./levelUp");
exports.levelUp = levelUp_1["default"];
var playGame_1 = require("./playGame");
exports.playGame = playGame_1["default"];
var dropSquares_1 = require("./dropSquares");
exports.dropSquares = dropSquares_1["default"];
var resetBoard_1 = require("./resetBoard");
exports.resetBoard = resetBoard_1["default"];
var globals_1 = require("./globals");
exports.numberOfSquares = globals_1.numberOfSquares;
exports.numberOfValues = globals_1.numberOfValues;
exports.randomValues = globals_1.randomValues;
