"use strict";
exports.__esModule = true;
var Gameboard_1 = require("./Gameboard/Gameboard");
exports.Gameboard = Gameboard_1["default"];
var Gameover_1 = require("./Gameover/Gameover");
exports.Gameover = Gameover_1["default"];
var Square_1 = require("./Square/Square");
exports.Square = Square_1["default"];
var Titlebar_1 = require("./Titlebar/Titlebar");
exports.Titlebar = Titlebar_1["default"];
var Boardframe_1 = require("./Boardframe/Boardframe");
exports.Boardframe = Boardframe_1["default"];
